### ISSUE TITLE
Rocket surfing

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#70] opened 2015-08-20 20:26 UTC
This is a very annoying bug.

Rockets can be walked on and jumped from. (Probably rolled from, too). It's just like you're walking on ground. So if you line up a great air-shot and hit your enemy's feet, he can just bounce off your rocket to safety, and even jump higher from it.

Should be that if you are touching a rocket with your feet, it blows up.

**Comment by Grab11** [comment] 2015-08-20 21:56
It can be fixed by removing rockets hp - pls do! no more selfkill cos friendly demp!

**Comment by deathsythe47** [comment] 2015-08-20 21:59
Friendly demp killing your rockets is fine, tech players just need to learn not to demp their own wookiees.

Rocket surfing is 100% shit though, I mean you can jump off rockets? WTF

**Comment by Grab11** [comment] 2015-08-20 22:04
Imo it's not fine, there is always demp spam, w/e if its enemy or friendly. 
But still, can be fixed by removing hp only.

**Comment by dpadgett** [comment] 2015-08-21 03:17
isn't that how a rocket should work though?  rockets only detonate if the tip impacts something.  if u stand on the propulsion side it shouldn't detonate.

**Comment by entdark** [comment] 2015-08-21 07:43
https://youtu.be/aF9aqZuidhI?t=2m5s
It's not a bug, it's a feature.

**Comment by deathsythe47** [comment] 2015-08-21 16:15
It might be useful for creating trick videos, but (at least in real-life siege games) it's bullshit.

https://www.youtube.com/watch?v=drcq6RK2V-w

I have never once seen any positives to this "feature" in a live game. All I have ever seen is people lining up nice airshots and getting robbed of their kills.

@dpadgett 
An impact on the tip of a real RPG doesn't directly cause detonation; decrease of forward motion does. (or timed fuse, or proximity sensors)
From [this website:](http://uxoinfo.com/blogcfc/client/includes/uxopages/Mulvaney_Details.cfm?Ord_Id=RF46)
"Either impact on the target **or deceleration from grazing** will cause the impact ball switch to close and deliver the electrical charge to the detonator, thus initiating the explosive train to the projectile."

As @Grab11 alluded to, I think this bug is an unintended side-effect of rockets being the only projectiles that can be shot out of the air. I'll do some experimenting later...

**Comment by entdark** [comment] 2015-08-21 21:12
I am ok if it be optional to please everyone.

**Comment by TheSil** [comment] 2015-08-21 22:19
I remember this has been asked several times on ctf too, definitely could put this under cvar. Now just to find this in code :)

**Comment by dpadgett** [comment] 2015-08-22 00:57
i don't think in ctf you would surf if the rocket hits lower half of your
body.  only if you actually stand on top of it.  your video seems to show
the person warping up on top of it?

**Comment by deathsythe47** [comment] 2015-08-22 02:07
Tested the cvar and it works great. Thanks

**Closed as completed** 2015-08-22 02:07 UTC
Labels: enhancement
